services:
  palpo:
    environment:
      PALPO_STORAGE__BACKEND: ${PALPO_STORAGE__BACKEND:-s3}
      PALPO_STORAGE__ENDPOINT: ${PALPO_STORAGE__ENDPOINT}
      PALPO_STORAGE__ACCESS_KEY_ID: ${PALPO_STORAGE__ACCESS_KEY_ID}
      PALPO_STORAGE__SECRET_ACCESS_KEY: ${PALPO_STORAGE__SECRET_ACCESS_KEY}
      PALPO_STORAGE__BUCKET: ${PALPO_STORAGE__BUCKET}
      PALPO_STORAGE__REGION: ${PALPO_STORAGE__REGION}
      PALPO_STORAGE__PREFIX: ${PALPO_STORAGE__PREFIX}
      PALPO_STORAGE__PATH_STYLE: ${PALPO_STORAGE__PATH_STYLE:-true}
      PALPO_STORAGE__REDIRECT: ${PALPO_STORAGE__REDIRECT:-true}
      PALPO_STORAGE__PRESIGN_EXPIRY: ${PALPO_STORAGE__PRESIGN_EXPIRY:-300}