[paths]
environments_path = "./environments"
extensions_dirs = [
    "extensions/backend",
    "extensions/database",
    "extensions"
]

[build]
skip_base_generation = true
extensions = ["fs-storage", "s3-storage", "postgresql", "pgrust", "oidc", "turn", "step-ca-trust"]

[build.combos]
entire = ["s3-storage", "pgrust", "oidc", "turn"]
entire-trust = ["s3-storage", "pgrust", "oidc", "turn", "step-ca-trust"]

[build.environments]
available = ["forwarding", "letsencrypt", "step-ca"]

[build.environments.forwarding]
extensions = []
combos = ["entire"]

[build.environments.letsencrypt]
extensions = []
combos = ["entire"]

[build.environments.step-ca]
extensions = []
combos = ["entire-trust"]
