[paths]
environments_path = "./environments"
extensions_dirs = [
    "extensions/database",
    "extensions"
]

[build]
skip_base_generation = true
extensions = ["postgresql", "pgrust", "turn", "step-ca-trust"]

[build.combos]
entire = ["pgrust", "turn"]
entire-trust = ["pgrust", "turn", "step-ca-trust"]

[build.environments]
available = ["forwarding", "internal", "letsencrypt", "step-ca"]

[build.environments.forwarding]
extensions = []
combos = ["entire"]

[build.environments.internal]
extensions = []
combos = ["entire"]

[build.environments.letsencrypt]
extensions = []
combos = ["entire"]

[build.environments.step-ca]
extensions = []
combos = ["entire"]
