x-logging: &default-logging
  driver: json-file
  options:
    max-size: ${LOG_MAX_SIZE:-10m}
    max-file: ${LOG_MAX_FILE:-3}
    compress: ${LOG_COMPRESS:-true}

services:
  palpo:
    container_name: palpo
    image: palpo
    build:
      context: .
      dockerfile_inline: |
        FROM ${IMAGE:-chrislearn/palpo:latest}
        RUN touch /var/palpo/palpo.toml
    restart: unless-stopped
    logging: *default-logging
    environment:
      PALPO_CONFIG: ${PALPO_CONFIG:-}
      PALPO_ADDRESS: ${PALPO_ADDRESS:-0.0.0.0:8008}
      PALPO_SERVER_NAME: ${PALPO_SERVER_NAME}
      PALPO_TRUSTED_SERVERS: ${PALPO_TRUSTED_SERVERS}
      PALPO_MAX_UPLOAD_SIZE: ${PALPO_MAX_UPLOAD_SIZE:-20000000}
      PALPO_ALLOW_REGISTRATION: ${PALPO_ALLOW_REGISTRATION:-false}
      # Extra
      PALPO_FEDERATION__ENABLE: ${PALPO_FEDERATION__ENABLE:-false}
      PALPO_PRESENCE__ALLOW_LOCAL: ${PALPO_PRESENCE__ALLOW_LOCAL:-true}
      # Security (Login)
      PALPO_RC_LOGIN__PER_SECOND: ${PALPO_RC_LOGIN__PER_SECOND:-9999.0}
      PALPO_RC_LOGIN__BURST: ${PALPO_RC_LOGIN__BURST:-9999}
      # Security (Registration)
      PALPO_RC_REGISTRATION__PER_SECOND: ${PALPO_RC_REGISTRATION__PER_SECOND:-9999.0}
      PALPO_RC_REGISTRATION__BURST: ${PALPO_RC_REGISTRATION__BURST:-9999}
      # Security (Password)
      PALPO_RC_PASSWORD__PER_SECOND: ${PALPO_RC_PASSWORD__PER_SECOND:-9999.0}
      PALPO_RC_PASSWORD__BURST: ${PALPO_RC_PASSWORD__BURST:-9999}
      # Security (Message)
      PALPO_RC_MESSAGE__PER_SECOND: ${PALPO_RC_MESSAGE__PER_SECOND:-9999.0}
      PALPO_RC_MESSAGE__BURST: ${PALPO_RC_MESSAGE__BURST:-9999}
    volumes:
      - palpo-media:/var/palpo/media
    networks:
      - palpo-network

volumes:
  palpo-media:
    name: palpo-media

networks:
  palpo-network:
    name: palpo-network