x-logging: &default-logging
  driver: json-file
  options:
    max-size: ${LOG_MAX_SIZE:-10m}
    max-file: ${LOG_MAX_FILE:-3}
    compress: ${LOG_COMPRESS:-true}

services:
  palpo:
    container_name: palpo
    image: ${IMAGE:-chrislearn/palpo:latest}
    restart: unless-stopped
    logging: *default-logging
    environment:
      PALPO_CONFIG: ${PALPO_CONFIG:-/var/palpo/palpo.toml}
      PALPO_ADDRESS: ${PALPO_ADDRESS:-0.0.0.0:8008}
      PALPO_SERVER_NAME: ${PALPO_SERVER_NAME}
      PALPO_TRUSTED_SERVERS: ${PALPO_TRUSTED_SERVERS}
      PALPO_ALLOW_REGISTRATION: ${PALPO_ALLOW_REGISTRATION:-false}
      PALPO_FEDERATION_ENABLE: ${PALPO_FEDERATION_ENABLE:-true}
      PALPO_PRESENCE_ALLOW_LOCAL: ${PALPO_PRESENCE_ALLOW_LOCAL:-true}
      PALPO_MAX_UPLOAD_SIZE: ${PALPO_MAX_UPLOAD_SIZE:-20000000}
    configs:
      - source: palpo-conf
        target: ${PALPO_CONFIG:-/var/palpo/palpo.toml}
    volumes:
      - palpo-media:/var/palpo/media
    networks:
      - palpo-network

configs:
  palpo-conf:
    content: |
      server_name = "${PALPO_SERVER_NAME}"
      # enable_admin_room = true
      # [admin]
      # room_notices = true
      # console_automatic = true

volumes:
  palpo-media:
    name: palpo-media

networks:
  palpo-network:
    name: palpo-network